package com.example.calculator.feature.presentation.util

import androidx.lifecycle.LiveData
import com.example.calculator.feature.domain.model.CalculationInfoItem

object DummyData {

    val list: List<CalculationInfoItem> = listOf(
        CalculationInfoItem(
            1,
            "Java",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            2,
            "Kotlin",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            3,
            "Python",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            4,
            "JavaScript",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            5,
            "Ruby",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            6,
            "Swift",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            7,
            "PHP",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            8,
            "Haskell",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            9,
            "RUST",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            10,
            "Go",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            11,
            "C",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            12,
            "C+",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            13,
            "C++",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            14,
            "C#",
            20220614L,
            1L
        ),
        CalculationInfoItem(
            15,
            "HTML",
            20220614L,
            1L
        ),
    )
}